PORCHIETTO_GestionSeguros/Controllers/RequerimientosController.cs
using NIXO_Framework;
using PORCHIETTO_GestionSeguros.Models.Empresas;
using PORCHIETTO_GestionSeguros.Models.Usuarios;
using PORCHIETTO_GestionSeguros.Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace PORCHIETTO_GestionSeguros.Controllers
{
    public class RequerimientosController : BaseController
    {
        #region Properties
        private IEmpresasService servicioEmpresas;

        public IEmpresasService GetServicioEmpresas()
        {
            return servicioEmpresas;
        }

        public void SetServicioEmpresas(IEmpresasService value)
        {
            servicioEmpresas = value;
        }

        private IRamasService servicioRamas;

        public IRamasService GetServicioRamas()
        {
            return servicioRamas;
        }

        public void SetServicioRamas(IRamasService value)
        {
            servicioRamas = value;
        }

        #endregion Properties

        #region Constructor
        public RequerimientosController(IEmpresasService ServicioEmpresas, IRamasService ServicioRamas)
        {
            this.SetServicioEmpresas(ServicioEmpresas);
            this.SetServicioRamas(ServicioRamas);
        }
        #endregion Constructor

        // GET: Requerimientos
        public ActionResult Index()
        {
            var model = GetServicioEmpresas().ObtenerRequerimientos();
            //ViewBag.Empresas = GetServicioEmpresas().ObtenerEmpresas().Lista;
            return View(model);
        }

        /// <summary>
        /// Agregar un nuevo Requerimiento
        /// </summary>
        /// <returns></returns>
        public ActionResult AgregarRequerimiento()
        {
            if (((List<NivelModel>)Session["niveles"]).Where(x => x.Nombre == Niveles.Administrador.ToString() || x.Nombre == Niveles.Empleado.ToString()).FirstOrDefault() != null)
            {
                return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult AgregarRequerimiento(AgregarRequerimientoModel model)
        {
            if (ModelState.IsValid)
            {
                AgregarRequerimientoRequest Requerimiento = new AgregarRequerimientoRequest
                {
                    Nombre = model.Nombre,
                };
                var response = GetServicioEmpresas().AgregarRequerimiento(Requerimiento);

                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        /// <summary>
        /// Modifica el requerimiento
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult ModificarRequerimiento(int Id)
        {
            var model = GetServicioEmpresas().ObtenerRequerimiento(Id);
            return View(model);
        }

        [HttpPost]
        public ActionResult ModificarRequerimiento(AgregarRequerimientoRequest model)
        {
            if (ModelState.IsValid)
            {
                ModificarRequerimientoRequest Medio = new ModificarRequerimientoRequest
                {
                    Id = model.Id,
                    Nombre = model.Nombre,
                };
                var response = GetServicioEmpresas().ModificarRequerimiento(Medio);

                return RedirectToAction("Index");

            }
            else
            {
                //notificacion.Mensaje = "Atención! Faltan datos o están incorrectos.";
                //notificacion.Tipo = "warning";
                //ViewBag.Notificar = notificacion;

                return View(model);
            }

        }

        /// <summary>
        /// Elimina el requerimiento seleccionado
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult EliminarRequerimiento(int Id)
        {
            GetServicioEmpresas().EliminarRequerimiento(Id);

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        #region REQUERIMIENTOS-EMPRESA
        public ActionResult ObtenerRequerimientosEmpresa(int IdEmpresa)
        {
            var Requerimientos = GetServicioEmpresas().ObtenerRequerimientosEmpresa(IdEmpresa).Lista;

            var lista = new List<ListItem> { };

            foreach (var item in Requerimientos)
            {
                lista.Add(new ListItem { Text = item.Nombre, Value = item.Id.ToString() });
            }

            return Json(lista, JsonRequestBehavior.AllowGet);
            //return lista;
        }

        /// <summary>
        /// Agrega un requerimiento de una lista a una empresa
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult AgregarRequerimientoEmpresa(int? Id)
        {
            if (((List<NivelModel>)Session["niveles"]).Where(x => x.Nombre == Niveles.Administrador.ToString() || x.Nombre == Niveles.Empleado.ToString()).FirstOrDefault() != null)
            {
                if (Id == null)
                    return RedirectToAction("Index", "Empresas");

                ViewBag.Empresa = GetServicioEmpresas().ObtenerEmpresa(Id ?? 1);
                ViewBag.ListaRamas = new SelectList(GetServicioRamas().ObtenerRamasEmpresa(Id ?? 1).Lista, "Id", "Nombre");
                ViewBag.ListaReq = new SelectList(GetServicioEmpresas().ObtenerRequerimientos().Lista, "Id", "Nombre");
                
                return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult AgregarRequerimientoEmpresa(AgregarRequerimientoEmpresaModel model)
        {
            if (ModelState.IsValid)
            {
                AgregarRequerimientoEmpresaRequest RequerimientoEmpresa = new AgregarRequerimientoEmpresaRequest
                {
                    Id_Empresa = model.Id_Empresa,
                    Id_Rama = model.Id_Rama,
                    Id_Requerimiento = model.Id_Requerimiento
                };
                var response = GetServicioEmpresas().AgregarRequerimientoEmpresa(RequerimientoEmpresa);

                return RedirectToAction("ListarRequerimientosEmpresa", "Empresas", new { Id = model.Id_Empresa});
            }
            else
            {
                return View(model);
            }
        }

        /// <summary>
        /// Elimina el requerimiento seleccionado de una empresa
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult EliminarRequerimientoEmpresa(int Id, int IdEmpresa)
        {
            GetServicioEmpresas().EliminarRequerimientoEmpresa(Id, IdEmpresa);

            return Json(true, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

PORCHIETTO_GestionSeguros/Views/Requerimientos/AgregarRequerimiento.cshtml
@model PORCHIETTO_GestionSeguros.Models.Empresas.AgregarRequerimientoModel
@{
    ViewBag.Title = "Requerimiento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h3>@ViewBag.Title</h3><small>Agregar</small>
                </div>
                <div class="x_content">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="pull-right">
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">
                                    <i class="fa fa-plus" aria-hidden="true"></i> Agregar
                                </button>
                                <a href="@Url.Action("Index", "Requerimientos")" class="btn btn-default">
                                    <i class="fa fa-times" aria-hidden="true"></i> <span>Cancelar</span>
                                </a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

PORCHIETTO_GestionSeguros/Views/Requerimientos/AgregarRequerimientoEmpresa.cshtml
@model PORCHIETTO_GestionSeguros.Models.Empresas.AgregarRequerimientoEmpresaModel

@{
    ViewBag.Title = "Requerimiento Empresa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h3>@ViewBag.Title</h3><small>Agregar</small>
                </div>
                <div class="x_content">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="row">
                                <label for="IdEmpresa" class="control-label col-md-2">Empresa</label>
                                <div class="form-group col-md-4">
                                    @Html.HiddenFor(model => model.Id_Empresa, new { id = "natureOfVisitField", Value = ((PORCHIETTO_GestionSeguros.Models.Empresas.ModificarEmpresaViewModel)ViewBag.Empresa).Id })
                                    @Html.Label(((PORCHIETTO_GestionSeguros.Models.Empresas.ModificarEmpresaViewModel)ViewBag.Empresa).Nombre.ToString(), htmlAttributes: new { @class = "control-label col-md-2" })
                                    @Html.ValidationMessageFor(model => model.Id_Empresa, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row">
                                <label for="Id_Rama" class="control-label col-md-2">Rama</label>
                                <div class="form-group col-md-4">
                                    @Html.DropDownListFor(model => model.Id_Rama, (SelectList)ViewBag.ListaRamas, "<Seleccione una Rama>", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Id_Rama, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row">
                                <label for="Id_Requerimiento" class="control-label col-md-2">Requerimiento</label>
                                <div class="form-group col-md-4">
                                    @Html.DropDownListFor(model => model.Id_Requerimiento, (SelectList)ViewBag.ListaReq, "<Seleccione un Requerimiento>", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Id_Requerimiento, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="pull-right">
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">
                                    <i class="fa fa-plus" aria-hidden="true"></i> Agregar
                                </button>
                                <a href="@Url.Action("ListarRequerimientosEmpresa", "Empresas", new { Id = ViewBag.Empresa.Id })" class="btn btn-default">
                                    <i class="fa fa-times" aria-hidden="true"></i> <span>Cancelar</span>
                                </a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

PORCHIETTO_GestionSeguros/Views/Requerimientos/Index.cshtml
@{
    ViewBag.Title = "Requerimientos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using PORCHIETTO_GestionSeguros.Models.Empresas;
@model RequerimientosModel

@Styles.Render("~/Content/BootstrapTable")
@Scripts.Render("~/bundles/BootstrapTable")
@Scripts.Render("~/bundles/Requerimientos")

<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="x_panel">
                <div class="x_title">
                    <h3>@ViewBag.Title</h3><small>Listado</small>
                </div>
                <div class="x_content">
                    <div class="">
                        <table id="TablaExtendida" class="table table-striped">
                            <thead class="bg-info">
                                <tr>
                                    <th data-sortable="true">Nombre</th>
                                    <th class="text-center">Modificar</th>
                                    <th class="text-center">Eliminar</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var tipo in Model.Lista)
                                {
                                    <tr id="@tipo.Id">
                                        <td>@tipo.Nombre</td>
                                        <td class="text-center"><a href="@Url.Action("ModificarRequerimiento", "Requerimientos" , new { Id = tipo.Id })"><span class="fa fa-edit" name="ModificarRequerimiento" data-toggle="tooltip" data-placement="bottom" data-original-title="Modificar"></span></a></td>
                                        <td class="text-center"><a href="javascript:EliminarRequerimiento(@tipo.Id);"><span class="fa fa-trash" name="EliminarRequerimiento" data-toggle="tooltip" data-placement="bottom" data-original-title="Eliminar"></span></a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="ln_solid"></div>
                    <a href="@Url.Action("AgregarRequerimiento", "Requerimientos" )" class="btn btn-success pull-right">
                        <i class="fa fa-plus" aria-hidden="true"></i> <span>Agregar</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

PORCHIETTO_GestionSeguros/Views/Requerimientos/ModificarRequerimiento.cshtml
@model PORCHIETTO_GestionSeguros.Models.Empresas.AgregarRequerimientoModel

@{
    ViewBag.Title = "Requerimiento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="">
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h3>@ViewBag.Title</h3><small>Modificar</small>
                </div>
                <div class="x_content">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)
                            <div class="row">
                                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="pull-right">
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">
                                    <i class="fa fa-floppy-o" aria-hidden="true"></i> Guardar
                                </button>
                                <a href="@Url.Action("Index", "Requerimientos")" class="btn btn-default">
                                    <i class="fa fa-times" aria-hidden="true"></i> <span>Cancelar</span>
                                </a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>