PORCHIETTO_GestionSeguros/Models/Notificaciones/MarcarResueltos.cs
using System.Collections.Generic;

namespace PORCHIETTO_GestionSeguros.Models.Notificaciones
{
    public class MarcarResueltos
    {
        public int IdNotificacion { get; set; }

        public int IdTipoNotificacion { get; set; }
    }

    public class MarcarResueltosResponse
    {

    }

    public class MarcarResueltosRequest
    {
        public List<MarcarResueltos> Lista { get; set; }
    }
}

PORCHIETTO_GestionSeguros/Models/Notificaciones/NotificacionesModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace PORCHIETTO_GestionSeguros.Models.Notificaciones
{
    public class NotificacionesModel
    {
        public class ObtenerNotificacionesRequest
        {
            public DateTime Fecha { get; set; }
            public int IdTipo { get; set; }
            public TipoNotificaciones Tipo { get; set; }
            public int IdProductor { get; set; }
            public int IdUsuario { get; set; }
        }

        public class ObtenerNotificacionesResponse
        {
            public List<ObtenerNotificacionesModel> Lista { get; set; }
        }

        public class ObtenerNotificacionesModel
        {
            public string Titulo { get; set; }
            public string Mensaje { get; set; }
            public int Cantidad { get; set; }
            TipoNotificaciones Tipo { get; set; }
            public string URL { get; set; }
        }
    }

    public class InformeViewModel
    {
        public TipoNotificaciones Tipo { get; set; }
        public List<Informe> Lista { get; set; }
    }

    public class Informe
    {
        public int Id { get; set; }
        public int IdTipo { get; set; }
        public TipoNotificaciones Tipo { get; set; }
        public string Numero { get; set; }
        public string Cliente { get; set; }
        public DateTime Vencimiento { get; set; }
        public string Mensaje { get; set; }
        public int IdProductor { get; set; }
        public int IdUsuario { get; set; }
    }

    public class ObtenerInformeRequest
    {
        public DateTime Fecha { get; set; }
        public TipoNotificaciones Tipo { get; set; }
        public int IdUsuario { get; set; }
        public int IdProductor { get; set; }
    }

    public class NotificacionesSiniestros
    {
        public int Id { get; set; }
        public int IdSiniestro { get; set; }
        public string Mensaje { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public DateTime? Borrado { get; set; }
        public bool VisibleCliente { get; set; }
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
    }

    public class InformeNotificacionesSiniestros
    {
        public string Cliente { get; set; }
        public int IdSiniestro { get; set; }
        public List<NotificacionesSiniestros> Lista { get; set; }
    }

    public class NotificacionesPolizas
    {
        public int Id { get; set; }
        public int IdPoliza { get; set; }
        public string Mensaje { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime? FechaFin { get; set; }
        public DateTime? Borrado { get; set; }
        public bool VisibleCliente { get; set; }
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
    }

    public class InformeNotificacionesPolizas
    {
        public string Cliente { get; set; }
        public int IdPoliza { get; set; }
        public List<NotificacionesPolizas> Lista { get; set; }
    }

    public enum TipoNotificaciones
    {
        [Description("Todas")] Todas,
        [Description("Vencimiento de Pólizas")] Vencimientos_Pólizas,
        [Description("Vencimiento de Siniestros")] Vencimientos_Siniestros,
        [Description("Notificaciones de Siniestros")] Notificaciones_Siniestros,
        [Description("Notificaciones de Pólizas")] Notificaciones_Pólizas
    }
}

PORCHIETTO_GestionSeguros/Controllers/NotificacionesController.cs
using NIXO_Framework;
using PORCHIETTO_GestionSeguros.Models.Notificaciones;
using PORCHIETTO_GestionSeguros.Models.Usuarios;
using PORCHIETTO_GestionSeguros.Servicios;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PORCHIETTO_GestionSeguros.Controllers
{
    public class NotificacionesController : BaseController
    {
        #region Properties
        private INotificacionesService servicioNotificaciones;

        public INotificacionesService GetServicioNotificaciones()
        {
            return servicioNotificaciones;
        }

        public void SetServicioNotificaciones(INotificacionesService value)
        {
            servicioNotificaciones = value;
        }
        #endregion Properties

        #region Constructor
        public NotificacionesController(INotificacionesService ServicioNotificaciones)
        {
            this.SetServicioNotificaciones(ServicioNotificaciones);
        }

        #endregion Constructor

        // GET: Notificaciones
        public ActionResult Index()
        {
            if (((List<NivelModel>)Session["niveles"]).Where(x => x.Nombre == Niveles.Administrador.ToString() 
            || x.Nombre == Niveles.Empleado.ToString()
            || x.Nombre == Niveles.Productor.ToString()).FirstOrDefault() != null)
            {
                return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }

        public ActionResult Informe(int Id)
        {
            if (((List<NivelModel>)Session["niveles"]).Where(x => x.Nombre == Niveles.Administrador.ToString() 
            || x.Nombre == Niveles.Empleado.ToString()
            || x.Nombre == Niveles.Productor.ToString()).FirstOrDefault() != null)
            {
                var dias = int.Parse(ConfigurationManager.AppSettings["DiasVencimiento"].ToString());
                var notificaciones = GetServicioNotificaciones().ObtenerInformeNotificaciones(new ObtenerInformeRequest
                {
                    Fecha = DateTime.Today.AddDays(dias),
                    Tipo = (TipoNotificaciones)Id,
                    IdUsuario = (int)Session["idproductor"] != 0 ? (int)Session["idusuario"] : 0,
                    IdProductor = (int)Session["idproductor"] != 0 ? (int)Session["idproductor"] : 0
                }).Lista.ToList();

                var model = new InformeViewModel
                {
                    Lista = notificaciones,
                    Tipo = (TipoNotificaciones)Id
                };

                return View(model);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult MarcarNotificacionesResueltas(List<MarcarResueltos> request)
        {
            GetServicioNotificaciones().MarcarResueltos(new MarcarResueltosRequest { Lista = request.ToList() });
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

PORCHIETTO_GestionSeguros/Controllers/SiniestrosController.cs
using NIXO_Framework;
using PORCHIETTO_GestionSeguros.Models.Notificaciones;
using PORCHIETTO_GestionSeguros.Models.Siniestros;
using PORCHIETTO_GestionSeguros.Models.Usuarios;
using PORCHIETTO_GestionSeguros.Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PORCHIETTO_GestionSeguros.Controllers
{
    public class SiniestrosController : BaseController
    {
        #region Properties
        private ISiniestrosService servicioSiniestros;
        private IClientesService servicioClientes;
        private IEmpresasService servicioEmpresas;
        private IProductoresService servicioProductores;
        private IRamasService servicioRamas;

        public ISiniestrosService GetServicioSiniestros()
        {
            return servicioSiniestros;
        }

        public void SetServicioSiniestros(ISiniestrosService value)
        {
            servicioSiniestros = value;
        }

        public IClientesService GetServicioClientes()
        {
            return servicioClientes;
        }

        public void SetServicioClientes(IClientesService value)
        {
            servicioClientes = value;
        }

        public IEmpresasService GetServicioEmpresas()
        {
            return servicioEmpresas;
        }

        public void SetServicioEmpresas(IEmpresasService value)
        {
            servicioEmpresas = value;
        }

        public IRamasService GetServicioRamas()
        {
            return servicioRamas;
        }

        public void SetServicioRamas(IRamasService value)
        {
            servicioRamas = value;
        }
        public IProductoresService GetServicioProductores()
        {
            return servicioProductores;
        }

        public void SetServicioProductores(IProductoresService value)
        {
            servicioProductores = value;
        }

        #endregion Properties

        #region Constructor
        public SiniestrosController(ISiniestrosService ServicioSiniestros,
            IClientesService ServicioClientes,
            IEmpresasService ServicioEmpresas,
            IRamasService ServicioRamas,
            IProductoresService ServicioProductores)
        {
            this.SetServicioSiniestros(ServicioSiniestros);
            this.SetServicioClientes(ServicioClientes);
            this.SetServicioEmpresas(ServicioEmpresas);
            this.SetServicioRamas(ServicioRamas);
            this.SetServicioProductores(ServicioProductores);
        }

        #endregion Constructor

        #region Siniestros

        // GET: Siniestros
        public ActionResult Index(int? id)
        {
            if (((List<NivelModel>)Session["niveles"]).Where(x => x.Nombre == Niveles.Administrador.ToString() 
            || x.Nombre == Niveles.Empleado.ToString()
            || x.Nombre == Niveles.Productor.ToString()).FirstOrDefault() != null)
            {
                ViewBag.Ramas = GetServicioRamas().ObtenerRama().Lista;

                var request = new SiniestroListadoRequest { };

                if ((int)Session["idproductor"] == 0)
                {
                    ViewBag.Productores = new SelectList(GetServicioProductores().ObtenerProductores().Lista, "Id", "Nombre");
                    request.IdProductor = id.HasValue ? id : 0;
                }
                else
                {
                    request.IdProductor = (int)Session["idproductor"];
                }

                var model = GetServicioSiniestros().ObtenerSiniestros(request);
                return View(model);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        public ActionResult AgregarSiniestro()
        {
            if (((List<NivelModel>)Session["niveles"]).Where(x => x.Nombre == Niveles.Administrador.ToString() || x.Nombre == Niveles.Empleado.ToString()).FirstOrDefault() != null)
            {
                ViewBag.Clientes = new SelectList(GetServicioClientes().ObtenerClientes().Lista, "Id", "NombreCompleto");
                ViewBag.Empresas = new SelectList(GetServicioEmpresas().ObtenerEmpresas().Lista, "Id", "Nombre");

                return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult AgregarSiniestro(AgregarSiniestroModel model)
        {
            if (((List<NivelModel>)Session["niveles"]).Where(x => x.Nombre == Niveles.Administrador.ToString() || x.Nombre == Niveles.Empleado.ToString()).FirstOrDefault() != null)
            {
                if (ModelState.IsValid)
                {
                    AgregarSiniestroRequest siniestro = new AgregarSiniestroRequest
                    {
                        Id = model.Id,
                        IdCliente = model.IdCliente,
                        FechaSiniestro = model.FechaSiniestro,
                        IdRama = model.IdRama,
                        IdEmpresa = model.IdEmpresa,
                        ApellidoNombreTercero = model.ApellidoNombreTercero,
                        TelefonoTercero = model.TelefonoTercero,
                        IdCompañiaTercero = model.IdCompañiaTercero,
                        IdRamaTercero = model.IdRamaTercero,
                        Observaciones = model.Observaciones,
                        Carpeta = model.Carpeta,
                        PresentaReclamoTercero = model.PresentaReclamoTercero
                    };

                    var idsin = GetServicioSiniestros().AgregarSiniestro(siniestro);

                    return RedirectToAction("RequerimientoDeSiniestro", new { id = idsin.Id });
                }
                else
                {
                    ViewBag.Clientes = new SelectList(GetServicioClientes().ObtenerClientes().Lista, "Id", "NombreCompleto");
                    ViewBag.Empresas = new SelectList(GetServicioEmpresas().ObtenerEmpresas().Lista, "Id", "Nombre");

                    return View(model);
                }

            }
            else
                return RedirectToAction("Index", "Home");
        }

        public ActionResult ModificarSiniestro(int Id)
        {
            if (((List<NivelModel>)Session["niveles"]).Where(x => x.Nombre == Niveles.Administrador.ToString() || x.Nombre == Niveles.Empleado.ToString()).FirstOrDefault() != null)
            {
                ViewBag.Clientes = new SelectList(GetServicioClientes().ObtenerClientes().Lista, "Id", "NombreCompleto");
                ViewBag.Empresas = new SelectList(GetServicioEmpresas().ObtenerEmpresas().Lista, "Id", "Nombre");
                var model = GetServicioSiniestros().ObtenerSiniestros(Id);
                ViewBag.Ramas = new SelectList(GetServicioRamas().ObtenerRamasEmpresa(model.IdEmpresa).Lista, "Id", "Nombre");
                if (model.IdCompañiaTercero != null)
                {
                    ViewBag.RamasTercero = new SelectList(GetServicioRamas().ObtenerRamasEmpresa(model.IdCompañiaTercero ?? 0).Lista, "Id", "Nombre");
                }
                return View(model);

            }
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult ModificarSiniestro(AgregarSiniestroModel model)
        {
            if (((List<NivelModel>)Session["niveles"]).Where(x => x.Nombre == Niveles.Administrador.ToString() || x.Nombre == Niveles.Empleado.ToString()).FirstOrDefault() != null)
            {
                if (ModelState.IsValid)
                {
                    ModificarSiniestroRequest siniestro = new ModificarSiniestroRequest
                    {
                        Id = model.Id,
                        IdCliente = model.IdCliente,
                        FechaSiniestro = model.FechaSiniestro,
                        IdRama = model.IdRama,
                        IdEmpresa = model.IdEmpresa,
                        ApellidoNombreTercero = model.ApellidoNombreTercero,
                        TelefonoTercero = model.TelefonoTercero,
                        IdCompañiaTercero = model.IdCompañiaTercero,
                        IdRamaTercero = model.IdRamaTercero,
                        Observaciones = model.Observaciones,
                        Carpeta = model.Carpeta,
                        PresentaReclamoTercero = model.PresentaReclamoTercero
                    };

                    GetServicioSiniestros().ModificarSiniestro(siniestro);

                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Clientes = new SelectList(GetServicioClientes().ObtenerClientes().Lista, "Id", "NombreCompleto");
                    ViewBag.Empresas = new SelectList(GetServicioEmpresas().ObtenerEmpresas().Lista, "Id", "Nombre");

                    return View(model);
                }

            }
            else
                return RedirectToAction("Index", "Home");
        }

        public ActionResult EliminarSiniestro(int Id)
        {
            if (((List<NivelModel>)Session["niveles"]).Where(x => x.Nombre == Niveles.Administrador.ToString() || x.Nombre == Niveles.Empleado.ToString()).FirstOrDefault() != null)
            {
                GetServicioSiniestros().EliminarSiniestro(Id);
                return Json(true, JsonRequestBehavior.AllowGet);

            }
            else
                return RedirectToAction("Index", "Home");
        }

        public ActionResult FinalizarSiniestro(int Id)
        {
            if (((List<NivelModel>)Session["niveles"]).Where(x => x.Nombre == Niveles.Administrador.ToString() || x.Nombre == Niveles.Empleado.ToString()).FirstOrDefault() != null)
            {
                GetServicioSiniestros().FinalizarSiniestro(Id);
                return Json(true, JsonRequestBehavior.AllowGet);

            }
            else
                return RedirectToAction("Index", "Home");

PORCHIETTO_GestionSeguros/Views/Siniestros/AgregarSiniestro.cshtml
@model PORCHIETTO_GestionSeguros.Models.Siniestros.AgregarSiniestroModel
@{
    ViewBag.Title = "Siniestro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/DatePicker")
@Styles.Render("~/Content/SelectPicker")
@Scripts.Render("~/bundles/AgregarSiniestro")
@Scripts.Render("~/bundles/SelectPicker")


<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h3>@ViewBag.Title</h3><small>Agregar</small>
                </div>
                <div class="x_content">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <div class="col-md-4 col-md-offset-1">
                                    @Html.LabelFor(model => model.IdCliente)
                                    @Html.DropDownListFor(model => model.IdCliente, (SelectList)ViewBag.Clientes, "<Seleccione un Cliente>", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.IdCliente, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-md-3 col-md-offset-1">
                                    @Html.LabelFor(model => model.FechaSiniestro)
                                    <div class='input-group date' id="FechaSiniestro">
                                        <span class="input-group-addon">
                                            <span class="fa fa-calendar"></span>
                                        </span>
                                        @Html.TextBoxFor(model => model.FechaSiniestro, new { @class = "form-control" })
                                    </div>
                                    @Html.ValidationMessageFor(model => model.FechaSiniestro, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4 col-md-offset-1">
                                    <label for="IdEmpresa">Empresa asegurado</label>
                                    @Html.DropDownListFor(model => model.IdEmpresa, (SelectList)ViewBag.Empresas, "<Seleccione una Empresa>", new { @class = "form-control selectPicker" })
                                    @Html.ValidationMessageFor(model => model.IdEmpresa, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-md-4 col-md-offset-1">
                                    @Html.LabelFor(model => model.IdRama)
                                    @Html.DropDownListFor(model => model.IdRama, Enumerable.Empty<SelectListItem>(), "<Seleccione una Rama>", new { @class = "form-control selectPicker" })
                                    @Html.ValidationMessageFor(model => model.IdRama, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <hr />
                            <div class="form-group">
                                <div class="col-md-4 col-md-offset-1">
                                    @Html.LabelFor(model => model.ApellidoNombreTercero)
                                    @Html.TextBoxFor(model => model.ApellidoNombreTercero, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ApellidoNombreTercero, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-md-4 col-md-offset-1">
                                    @Html.LabelFor(model => model.IdCompañiaTercero)
                                    @Html.DropDownListFor(model => model.IdCompañiaTercero, (SelectList)ViewBag.Empresas, "<Seleccione una Empresa>", new { @class = "form-control selectPicker" })
                                    @Html.ValidationMessageFor(model => model.IdCompañiaTercero, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4 col-md-offset-1">
                                    @Html.LabelFor(model => model.TelefonoTercero)
                                    @Html.TextBoxFor(model => model.TelefonoTercero, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.TelefonoTercero, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-md-4 col-md-offset-1">
                                    @Html.LabelFor(model => model.IdRamaTercero)
                                    @Html.DropDownListFor(model => model.IdRamaTercero, Enumerable.Empty<SelectListItem>(), "<Seleccione una Rama>", new { @class = "form-control selectPicker" })
                                    @Html.ValidationMessageFor(model => model.IdRamaTercero, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <hr />
                            <div class="form-group">
                                <div class="col-md-4 col-md-offset-1">
                                    @Html.LabelFor(model => model.Carpeta)
                                    @Html.TextBoxFor(model => model.Carpeta, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Carpeta, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-9 col-md-offset-1">
                                    @Html.LabelFor(model => model.Observaciones)
                                    @Html.TextAreaFor(model => model.Observaciones, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="pull-right">
                            <button type="submit" class="btn btn-success">
                                <i class="fa fa-plus" aria-hidden="true"></i> Agregar
                            </button>
                            <a href="@Url.Action("Index", "Siniestros")" class="btn btn-default">
                                <i class="fa fa-times" aria-hidden="true"></i> <span>Cancelar</span>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

PORCHIETTO_GestionSeguros/Views/Siniestros/MisSiniestros.cshtml
@using PORCHIETTO_GestionSeguros.Models.Siniestros;
@model SiniestroModel

@{
    ViewBag.Title = "Mis Siniestros";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/BootstrapTable")
@Scripts.Render("~/bundles/BootstrapTable")
@Scripts.Render("~/bundles/Siniestros")

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h3>@ViewBag.Title</h3>
                </div>
                <div class="x_content">
                    <div class="">
                        <table id="TablaExtendida" class="table table-striped">
                            <thead class="bg-info">
                                <tr>
                                    <th data-sortable="true">ID</th>
                                    <th data-sortable="true">Fecha Siniestro</th>
                                    <th data-sortable="true">Rama</th>
                                    <th class="text-center">Visualizar</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Lista)
                                {
                                    <tr id="@item.Id">
                                        <td>@item.Id</td>
                                        <td class="text-center">@(item.FechaSiniestro.HasValue ? item.FechaSiniestro.Value.ToString(@"dd\/MM\/yyyy") : "")</td>
                                        <td>@item.Rama</td>
                                        <td><a href="@Url.Action("VerSiniestro", "Siniestros", new { Id = item.Id })"><span class="fa fa-eye" name="VerSiniestro" title="Ver"></span></a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="ln_solid"></div>
                </div>
            </div>
        </div>
    </div>
</div>

PORCHIETTO_GestionSeguros/Views/Siniestros/RequerimientoDeSiniestro.cshtml
@model PORCHIETTO_GestionSeguros.Models.Siniestros.RequerimientosSiniestroModel
@{
    ViewBag.Title = "Requerimiento De Siniestro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="x_panel">
                <div class="x_title">
                    @Html.HiddenFor(model => model.IdSiniestro, Model.IdSiniestro)
                    <h3>@ViewBag.Title</h3><small>Nº: @Html.LabelFor(model => model.IdSiniestro, Model.IdSiniestro.ToString())</small>
                </div>
                <div class="x_content">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-1">
                                    <label for="IdEmpresa">Empresa Asegurado: </label>
                                    @Html.LabelFor(model => model.DescripEmpresa, Model.DescripEmpresa)
                                </div>
                                <div class="col-sm-4 col-sm-offset-1">
                                    <label for="IdEmpresa">Empresa Tercero: </label>
                                    @Html.LabelFor(model => model.DescripEmpresaTercero, Model.DescripEmpresaTercero)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-1">
                                    @for (int i = 0; i < Model.ListaReqEmpresa.Count(); i++)
                                    {
                                    <div class="col-sm-12">
                                        @Html.CheckBoxFor(model => model.ListaReqEmpresa[i].Valor, Model.ListaReqEmpresa[i].Valor)
                                        @Html.LabelFor(model => model.ListaReqEmpresa[i].DescripRequerimiento, Model.ListaReqEmpresa[i].DescripRequerimiento)
                                        @Html.HiddenFor(model => model.ListaReqEmpresa[i].IdRequerimientoEmpresa, Model.ListaReqEmpresa[i].IdRequerimientoEmpresa)
                                        @Html.HiddenFor(model => model.ListaReqEmpresa[i].IdSiniestro, Model.ListaReqEmpresa[i].IdSiniestro)
                                        @Html.HiddenFor(model => model.ListaReqEmpresa[i].Principal, Model.ListaReqEmpresa[i].Principal)
                                        @Html.HiddenFor(model => model.ListaReqEmpresa[i].Id, Model.ListaReqEmpresa[i].Id)
                                    </div>
                                    }
                                </div>
                                <div class="col-sm-4 col-sm-offset-1">
                                    @if (Model.ListaReqEmpresaTercero.Count() > 0)
                                    {
                                        for (int j = 0; j < Model.ListaReqEmpresaTercero.Count(); j++)
                                        {
                                    <div class="col-sm-12">
                                        @Html.CheckBoxFor(model => model.ListaReqEmpresaTercero[j].Valor, Model.ListaReqEmpresaTercero[j].Valor)
                                        @Html.LabelFor(model => model.ListaReqEmpresaTercero[j].DescripRequerimiento, Model.ListaReqEmpresaTercero[j].DescripRequerimiento)
                                        @Html.HiddenFor(model => model.ListaReqEmpresaTercero[j].IdRequerimientoEmpresa, Model.ListaReqEmpresaTercero[j].IdRequerimientoEmpresa)
                                        @Html.HiddenFor(model => model.ListaReqEmpresaTercero[j].IdSiniestro, Model.ListaReqEmpresaTercero[j].IdSiniestro)
                                        @Html.HiddenFor(model => model.ListaReqEmpresaTercero[j].Principal, Model.ListaReqEmpresaTercero[j].Principal)
                                        @Html.HiddenFor(model => model.ListaReqEmpresaTercero[j].Id, Model.ListaReqEmpresaTercero[j].Id)
                                    </div>
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="pull-right">
                            <button type="submit" class="btn btn-success">
                                <i class="fa fa-plus" aria-hidden="true"></i> Agregar
                            </button>
                            <a href="@Url.Action("Index", "Siniestros")" class="btn btn-default">
                                <i class="fa fa-times" aria-hidden="true"></i> <span>Cancelar</span>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>